version: '3'

services:
  web-api:
    image: golang:1.19
    container_name: todoAPI-web-service
    environment:
      CONNECTION_DBURL: ${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?parseTime=true
    working_dir: /app/todoAPI
    volumes: 
      - ./web-api:/app/todoAPI
    ports:
      - 8100:8100
    depends_on:
      - db
    networks:
      - backbone
    command: sh -c "go mod vendor && go run main.go"
  db:
    container_name: todoAPI-database-service
    build:
      context: ./maria-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./volumes/database:/var/lib/mysql
    ports:
      - 3406:3306
    networks:
      - backbone
networks:
  backbone:
    driver: bridge