version: '3'

services:
  web-api:
    container_name: todoapi-web-service
    image: todoapi-web-image
    build: 
      context: ./web-api
    environment:
      CONNECTION_DBURL: ${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?parseTime=true
      CORS_TARGET: ${WEB_CORS_TARGET}
    working_dir: /app/todoAPI

    ports:
      - 8100:8100
    depends_on:
      - db
    networks:
      - backbone

  db:
    container_name: todoapi-database-service
    image: todoapi-database-image
    build:
      context: ./maria-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./volumes/database:/var/lib/mysql
    ports:
      - 3406:3306
    networks:
      - backbone
networks:
  backbone:
    driver: bridge